import type { Layout } from "../patch";

// Complete, ready-to-play patches. Loading one replaces the canvas.
export type Setup = { id: string; title: string; description: string; layout: Layout };

const C2 = 65.41;
const C4 = 261.63;
const C5 = 523.25;

// Sequencer steps are hidden params s0..s7 (semitones) and g0..g7 (gate on/off).
function steps(semis: number[], gates: boolean[] = semis.map(() => true)) {
  return Object.fromEntries([
    ...semis.map((v, i) => [`s${i}`, v]),
    ...gates.map((g, i) => [`g${i}`, g]),
  ]);
}

// Beat grid patterns are written in 8th notes (the clock's 1/8 output).
const FOUR_ON_FLOOR = "x.x.x.x.x.x.x.x.";
const BACKBEAT = "..x...x...x...x.";
const OFFBEAT_HATS = ".x.x.x.x.x.x.x.x";

export const SETUPS: Setup[] = [
  {
    id: "techno-loop",
    title: "techno loop",
    description: "Four-on-the-floor drums and a filtered saw bassline from the step sequencer, glued with a compressor.",
    layout: {
      modules: [
        { kind: "clock", x: 0, y: 0, params: { bpm: 128 } },
        {
          kind: "beatgrid",
          x: 280,
          y: 0,
          params: { t0: FOUR_ON_FLOOR, t1: BACKBEAT, t2: OFFBEAT_HATS, t3: "..........x....x" },
        },
        { kind: "kick", x: 760, y: -80, collapsed: true, params: { tone: 0.35, decay: 0.45 } },
        { kind: "snare", x: 760, y: 70, collapsed: true, params: { level: 0.55 } },
        { kind: "hat", x: 760, y: 220, collapsed: true, params: { decay: 0.08, level: 0.45 } },
        { kind: "clap", x: 760, y: 370, collapsed: true, params: { level: 0.5 } },
        { kind: "mixer", x: 1020, y: 40, collapsed: true },
        {
          kind: "sequencer",
          x: 280,
          y: 300,
          params: steps([0, 0, 12, 0, 3, 0, -2, 7], [true, true, true, true, true, false, true, true]),
        },
        { kind: "oscillator", x: 680, y: 560, collapsed: true, params: { wave: "sawtooth", freq: C2, on: true } },
        {
          kind: "envelope",
          x: 680,
          y: 740,
          collapsed: true,
          params: { attack: 0.002, decay: 0.16, sustain: 0, release: 0.08 },
        },
        { kind: "filter", x: 940, y: 560, collapsed: true, params: { cutoff: 220, q: 9, mod: 3.5 } },
        { kind: "vca", x: 1200, y: 560, collapsed: true },
        { kind: "mixer", x: 1280, y: 40, collapsed: true, params: { ch2: 0.7 } },
        { kind: "compressor", x: 1540, y: 40, collapsed: true, params: { threshold: -18, ratio: 4, makeup: 4 } },
        { kind: "reverb", x: 1800, y: 40, collapsed: true, params: { size: 1.5, mix: 0.12 } },
        { kind: "speaker", x: 2060, y: 40, params: { volume: 0.6 } },
      ],
      cables: [
        [0, "x2", 1, "clock"],
        [0, "x2", 7, "clock"],
        [1, "t0", 2, "trig"],
        [1, "t1", 3, "trig"],
        [1, "t2", 4, "trig"],
        [1, "t3", 5, "trig"],
        [2, "out", 6, "in1"],
        [3, "out", 6, "in2"],
        [4, "out", 6, "in3"],
        [5, "out", 6, "in4"],
        [7, "pitch", 8, "pitch"],
        [7, "gate", 9, "gate"],
        [8, "out", 10, "in"],
        [10, "out", 11, "in"],
        [9, "out", 11, "cv"],
        [9, "out", 10, "cutoff"],
        [6, "out", 12, "in1"],
        [11, "out", 12, "in2"],
        [12, "out", 13, "in"],
        [13, "out", 14, "in"],
        [14, "out", 15, "in"],
      ],
    },
  },
  {
    id: "sh-bleeps",
    title: "sample & hold bleeps",
    description: "The classic: a random voltage on every clock tick sets the pitch. Computer-lab bleeps into a dotted echo.",
    layout: {
      modules: [
        { kind: "clock", x: 0, y: 0, params: { bpm: 100 } },
        { kind: "random", x: 260, y: 0 },
        { kind: "attenuverter", x: 520, y: 0, params: { scale: 1.2, offset: 0.4 } },
        { kind: "oscillator", x: 780, y: 0, params: { wave: "triangle", freq: C5, on: true } },
        { kind: "envelope", x: 780, y: 320, params: { attack: 0.002, decay: 0.12, sustain: 0, release: 0.12 } },
        { kind: "vca", x: 1060, y: 0 },
        { kind: "delay", x: 1560, y: 0, params: { time: 0.45, feedback: 0.5, mix: 0.4 } },
        { kind: "reverb", x: 1820, y: 0, params: { size: 4, mix: 0.35 } },
        { kind: "speaker", x: 2080, y: 0, params: { volume: 0.5 } },
        { kind: "scope", x: 1300, y: 0, params: { time: 60 } },
      ],
      cables: [
        [0, "x2", 1, "trig"],
        [1, "out", 2, "in"],
        [2, "out", 3, "pitch"],
        [0, "x2", 4, "gate"],
        [3, "out", 5, "in"],
        [4, "out", 5, "cv"],
        [5, "out", 9, "in"],
        [9, "thru", 6, "in"],
        [6, "out", 7, "in"],
        [7, "out", 8, "in"],
      ],
    },
  },
  {
    id: "fm-bells",
    title: "fm bells",
    description: "Play the keyboard (a–;). A modulator oscillator bends the carrier's frequency; the envelope makes each note ring and darken.",
    layout: {
      modules: [
        { kind: "keyboard", x: 0, y: 60 },
        { kind: "oscillator", x: 380, y: 0, params: { wave: "sine", freq: C4 * 1.4, level: 1, on: true } },
        { kind: "envelope", x: 380, y: 330, params: { attack: 0.002, decay: 1.5, sustain: 0, release: 1.8 } },
        { kind: "vca", x: 660, y: 0 },
        { kind: "attenuverter", x: 900, y: 0, params: { scale: 2 } },
        { kind: "oscillator", x: 1140, y: 0, params: { wave: "sine", freq: C4, level: 0.6, on: true } },
        { kind: "vca", x: 1420, y: 0 },
        { kind: "reverb", x: 1660, y: 0, params: { size: 5, mix: 0.4, bright: 0.6 } },
        { kind: "speaker", x: 1920, y: 0 },
      ],
      cables: [
        [0, "pitch", 1, "pitch"],
        [0, "pitch", 5, "pitch"],
        [0, "gate", 2, "gate"],
        [1, "out", 3, "in"],
        [2, "out", 3, "cv"],
        [3, "out", 4, "in"],
        [4, "out", 5, "fm"],
        [5, "out", 6, "in"],
        [2, "out", 6, "cv"],
        [6, "out", 7, "in"],
        [7, "out", 8, "in"],
      ],
    },
  },
  {
    id: "wobble-bass",
    title: "wobble bass",
    description: "Two detuned oscillators through a resonant filter swept by an LFO. Hold a key on the keyboard (a–;); turn the LFO rate.",
    layout: {
      modules: [
        { kind: "keyboard", x: 0, y: 60, params: { glide: 0.06 } },
        { kind: "oscillator", x: 380, y: 0, collapsed: true, params: { wave: "sawtooth", freq: C2, level: 0.5, on: true } },
        { kind: "oscillator", x: 380, y: 190, collapsed: true, params: { wave: "square", freq: C2 * 1.006, level: 0.35, on: true } },
        { kind: "mixer", x: 640, y: 0, collapsed: true },
        { kind: "lfo", x: 640, y: 260, params: { wave: "sine", rate: 4, depth: 0.9 } },
        { kind: "filter", x: 900, y: 0, params: { cutoff: 300, q: 10, mod: 2.5 } },
        { kind: "waveshaper", x: 1180, y: 0, collapsed: true, params: { drive: 3, level: 0.5 } },
        { kind: "envelope", x: 900, y: 320, collapsed: true, params: { attack: 0.005, decay: 0.2, sustain: 0.8, release: 0.15 } },
        { kind: "vca", x: 1440, y: 0, collapsed: true },
        { kind: "compressor", x: 1700, y: 0, collapsed: true },
        { kind: "speaker", x: 1960, y: 0 },
      ],
      cables: [
        [0, "pitch", 1, "pitch"],
        [0, "pitch", 2, "pitch"],
        [1, "out", 3, "in1"],
        [2, "out", 3, "in2"],
        [3, "out", 5, "in"],
        [4, "out", 5, "cutoff"],
        [5, "out", 6, "in"],
        [6, "out", 8, "in"],
        [0, "gate", 7, "gate"],
        [7, "out", 8, "cv"],
        [8, "out", 9, "in"],
        [9, "out", 10, "in"],
      ],
    },
  },
  {
    id: "ocean",
    title: "ocean waves",
    description: "Pink noise, a slow LFO swelling the volume and another sweeping the filter. Surf in a big room.",
    layout: {
      modules: [
        { kind: "noise", x: 0, y: 0, params: { color: "pink", level: 0.6 } },
        { kind: "filter", x: 260, y: 0, params: { cutoff: 600, q: 0.7, mod: 2 } },
        { kind: "vca", x: 540, y: 0, params: { bias: 0.05 } },
        { kind: "lfo", x: 0, y: 260, params: { wave: "sine", rate: 0.09, depth: 0.9, unipolar: true } },
        { kind: "lfo", x: 260, y: 320, params: { wave: "triangle", rate: 0.13, depth: 0.8 } },
        { kind: "reverb", x: 800, y: 0, params: { size: 6, mix: 0.5, bright: 0.4 } },
        { kind: "spectrum", x: 1060, y: 0 },
        { kind: "speaker", x: 1360, y: 0, params: { volume: 0.6 } },
      ],
      cables: [
        [0, "out", 1, "in"],
        [1, "out", 2, "in"],
        [3, "out", 2, "cv"],
        [4, "out", 1, "cutoff"],
        [2, "out", 5, "in"],
        [5, "out", 6, "in"],
        [6, "thru", 7, "in"],
      ],
    },
  },
  {
    id: "ambient",
    title: "generative ambient",
    description: "A slow pentatonic sequence on the celesta wavetable, random filter drift, chorus, long echoes and a huge reverb.",
    layout: {
      modules: [
        { kind: "clock", x: 0, y: 0, params: { bpm: 36 } },
        {
          kind: "sequencer",
          x: 260,
          y: 0,
          params: steps([0, 7, 3, 10, 5, 12, 7, 15], [true, false, true, true, false, true, true, false]),
        },
        { kind: "wavetable", x: 680, y: 0, collapsed: true, params: { table: "celesta", freq: C4, level: 0.5, on: true } },
        { kind: "envelope", x: 680, y: 190, collapsed: true, params: { attack: 0.01, decay: 2, sustain: 0.15, release: 3 } },
        { kind: "vca", x: 940, y: 0, collapsed: true },
        { kind: "random", x: 260, y: 290, params: { range: 0.6, slew: 0.4 } },
        { kind: "filter", x: 1200, y: 0, collapsed: true, params: { cutoff: 1800, q: 2, mod: 2 } },
        { kind: "chorus", x: 1460, y: 0, collapsed: true },
        { kind: "delay", x: 1720, y: 0, collapsed: true, params: { time: 0.83, feedback: 0.6, tone: 2500, mix: 0.45 } },
        { kind: "reverb", x: 1980, y: 0, collapsed: true, params: { size: 7, mix: 0.55 } },
        { kind: "speaker", x: 2240, y: 0, params: { volume: 0.6 } },
      ],
      cables: [
        [0, "x1", 1, "clock"],
        [1, "pitch", 2, "pitch"],
        [1, "gate", 3, "gate"],
        [2, "out", 4, "in"],
        [3, "out", 4, "cv"],
        [4, "out", 6, "in"],
        [0, "d4", 5, "trig"],
        [5, "out", 6, "cutoff"],
        [6, "out", 7, "in"],
        [7, "out", 8, "in"],
        [8, "out", 9, "in"],
        [9, "out", 10, "in"],
      ],
    },
  },
  {
    id: "arp-drums",
    title: "arp + drums",
    description: "Press a key (a–;) to start a latched minor-7th arpeggio over a kick, clap and hat groove.",
    layout: {
      modules: [
        { kind: "keyboard", x: 0, y: 420 },
        { kind: "clock", x: 0, y: 0, params: { bpm: 124 } },
        { kind: "arpeggiator", x: 380, y: 420, params: { chord: "m7", pattern: "updown", octaves: 2, latch: true } },
        { kind: "oscillator", x: 700, y: 420, collapsed: true, params: { wave: "sawtooth", level: 0.4, on: true } },
        { kind: "filter", x: 960, y: 420, collapsed: true, params: { cutoff: 1400, q: 5, mod: 2 } },
        { kind: "envelope", x: 700, y: 610, collapsed: true, params: { attack: 0.002, decay: 0.15, sustain: 0.1, release: 0.15 } },
        { kind: "vca", x: 1220, y: 420, collapsed: true },
        { kind: "delay", x: 1480, y: 420, collapsed: true, params: { time: 0.363, feedback: 0.45, mix: 0.3 } },
        { kind: "beatgrid", x: 280, y: 0, params: { t0: FOUR_ON_FLOOR, t1: BACKBEAT, t2: OFFBEAT_HATS, t3: "" } },
        { kind: "kick", x: 760, y: -40, collapsed: true },
        { kind: "clap", x: 760, y: 110, collapsed: true, params: { level: 0.5 } },
        { kind: "hat", x: 760, y: 260, collapsed: true, params: { decay: 0.1, level: 0.4 } },
        { kind: "mixer", x: 1740, y: 100, collapsed: true, params: { ch4: 0.7 } },
        { kind: "reverb", x: 2000, y: 100, collapsed: true, params: { size: 2, mix: 0.15 } },
        { kind: "speaker", x: 2260, y: 100 },
      ],
      cables: [
        [1, "x2", 8, "clock"],
        [1, "x2", 2, "clock"],
        [0, "pitch", 2, "pitch"],
        [0, "gate", 2, "gate"],
        [2, "pitch", 3, "pitch"],
        [2, "gate", 5, "gate"],
        [3, "out", 4, "in"],
        [4, "out", 6, "in"],
        [5, "out", 6, "cv"],
        [5, "out", 4, "cutoff"],
        [6, "out", 7, "in"],
        [8, "t0", 9, "trig"],
        [8, "t1", 10, "trig"],
        [8, "t2", 11, "trig"],
        [9, "out", 12, "in1"],
        [10, "out", 12, "in2"],
        [11, "out", 12, "in3"],
        [7, "out", 12, "in4"],
        [12, "out", 13, "in"],
        [13, "out", 14, "in"],
      ],
    },
  },
  {
    id: "scope-lab",
    title: "scope lab",
    description: "See sound: a slowly bending oscillator through the scope, tuner and spectrum. Try the waveforms.",
    layout: {
      modules: [
        { kind: "oscillator", x: 0, y: 0, params: { wave: "sine", freq: 110, level: 0.4, on: true } },
        { kind: "lfo", x: 0, y: 320, params: { wave: "triangle", rate: 0.15, depth: 0.3 } },
        { kind: "scope", x: 300, y: 0 },
        { kind: "tuner", x: 600, y: 0 },
        { kind: "spectrum", x: 860, y: 0 },
        { kind: "speaker", x: 1160, y: 0, params: { volume: 0.25 } },
      ],
      cables: [
        [1, "out", 0, "pitch"],
        [0, "out", 2, "in"],
        [2, "thru", 3, "in"],
        [3, "thru", 4, "in"],
        [4, "thru", 5, "in"],
      ],
    },
  },
];
